spring.application.name=pc1

spring.datasource.url=jdbc:postgresql://localhost:5446/shop
spring.datasource.username=admin
spring.datasource.password=1X1X

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true